// Copyright (c) Aura development team - Licensed under GNU GPL
// For more information, see license file in the main folder

namespace Aura.Mabi.Const
{
	public enum Stat : byte
	{
		Name,
		Title,
		EngTitle,
		Type,
		SkinColor,
		EyeType,
		EyeColor,
		MouthType,
		State,
		StateEx,
		StateEx2, // [180300, NA166 (18.09.2013)]
		Height,
		Weight,
		Upper,
		Lower,
		RegionId,
		PositionX,
		PositionY,
		Direction,
		BattleState,
		WeaponSet,
		Extra1,
		Extra2,
		Extra3,
		CombatPower,
		MotionType,
		Life,
		LifeInjured,
		LifeMax,
		LifeMaxMod,
		Mana,
		ManaMax,
		ManaMaxMod,
		Stamina,
		StaminaMax,
		StaminaMaxMod,
		Hunger,
		FoodMinRatio,
		Level,
		LevelTotal,
		LevelMax,
		RebirthCount,
		LifeTimeSkill,
		Experience,
		Age,
		Str,
		StrMod,
		Dex,
		DexMod,
		Int,
		IntMod,
		Will,
		WillMod,
		Luck,
		LuckMod,
		LifeMaxFoodMod,
		ManaMaxFoodMod,
		StaminaMaxFoodMod,
		StrFoodMod,
		DexFoodMod,
		IntFoodMod,
		WillFoodMod,
		LuckFoodMod,
		AbilityPoints,
		AttackMinBase,
		AttackMinMod,
		AttackMaxBase,
		AttackMaxMod,
		InjuryMinBase,
		InjuryMinMod,
		InjuryMaxBase,
		InjuryMaxMod,
		LeftAttackMinMod,
		LeftAttackMaxMod,
		RightAttackMinMod,
		RightAttackMaxMod,
		LeftInjuryMinMod,
		LeftInjuryMaxMod,
		RightInjuryMinMod,
		RightInjuryMaxMod,
		LeftCriticalMod,
		RightCriticalMod,
		LeftBalanceMod,
		RightBalanceMod,
		MagicDefenseMod,
		MagicProtectionMod, // [180300, NA166 (18.09.2013)]
		MagicAttackMod,
		MeleeAttackRateMod,
		RangeAttackRateMod,
		CriticalBase,
		CriticalMod,
		ProtectionBase,
		ProtectionMod,
		DefenseBase,
		DefenseMod,
		BalanceBase,
		BalanceMod,
		Rank1,
		Rank2,
		ArmorPierceMod, // [180300, NA166 (18.09.2013)]
		Score,
		AttackMinBaseMod,
		AttackMaxBaseMod,
		InjuryMinBaseMod,
		InjuryMaxBaseMod,
		CriticalBaseMod,
		ProtectionBaseMod,
		DefenseBaseMod,
		BalanceBaseMod,
		MeleeAttackMinBaseMod,
		MeleeAttackMaxBaseMod,
		MeleeInjuryMinBaseMod,
		MeleeInjuryMaxBaseMod,
		RangeAttackMinBaseMod,
		RangeAttackMaxBaseMod,
		RangeInjuryMinBaseMod,
		RangeInjuryMaxBaseMod,
		DualgunAttackMinBaseMod, // [180300, NA166 (18.09.2013)]
		DualgunAttackMaxBaseMod, // [180300, NA166 (18.09.2013)]
		DualgunInjuryMinBaseMod, // [180300, NA166 (18.09.2013)]
		DualgunInjuryMaxBaseMod, // [180300, NA166 (18.09.2013)]

		// [20XXXX?, NA2XX? (XX.XX.2016?)]
		// New stats were added somewhere, which shifted the Toxic group
		// by 4. It's unknown when they were added, what they do,
		// and where *exactly* they go, but since it's 4, it might be a
		// new weapon type.
		Unknown1,
		Unknown2,
		Unknown3,
		Unknown4,

		PoisonBase,
		PoisonMod,
		PoisonImmuneBase,
		PoisonImmuneMod,
		PoisonDamageRatio1,
		PoisonDamageRatio2,
		CombatPowerMod,
		CumulateStr,
		CumulateDex,
		CumulateInt,
		CumulateWill,
		CumulateLuck,
		CumulateHeight,
		CumulateFatness,
		CumulateUpper,
		CumulateLower,
		CumulateLife,
		CumulateMana,
		CumulateStamina,
		Toxic,
		ToxicDrunkenTime,
		ToxicStr,
		ToxicInt,
		ToxicDex,
		ToxicWill,
		ToxicLuck,
		LastTown,
		LastDungeon,
		ExploLevel,
		ExploMaxKeyLevel,
		ExploCumLevel,
		ExploExp,
		DiscoverCount,
		ConditionStr,
		ConditionInt,
		ConditionDex,
		ConditionWill,
		ConditionLuck,
		ElementPhysical,
		ElementLightning,
		ElementFire,
		ElementIce,
		BareAttackMin,
		BareAttackMax,
		BareInjuryMin,
		BareInjuryMax,
		BareCritical,
		BareRate,

		None = 0xFF,
	}
}
