ALTER TABLE `contacts` ADD `status` INT NOT NULL DEFAULT '224' , ADD `chatOptions` INT NOT NULL DEFAULT '-2147483648' , ADD `nickname` VARCHAR(127) NOT NULL DEFAULT '' ;
ALTER TABLE `contacts` CHANGE `status` `status` TINYINT UNSIGNED NOT NULL DEFAULT '224', CHANGE `chatOptions` `chatOptions` INT UNSIGNED NOT NULL DEFAULT '2147483648';
